name: cmpets
description: A new Flutter project.
version: 1.0.4+70
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.1
  table_calendar: ^3.0.9  # for displaying a calendar in the dialog
  device_calendar: ^4.3.2
  timezone: ^0.9.2  # Add this line
  firebase_core: ^3.4.0
  flutterfire_cli: ^0.2.7
  flutter_svg: ^2.0.9
  envied: ^0.5.1
  flutter_svg_provider: ^1.0.3
  firebase_auth: ^5.2.0
  intl: ^0.18.0
  image_picker: ^0.8.4  # Add the latest version
  permission_handler: ^11.0.1
  carousel_slider_plus: ^6.0.0
  flutter_barcode_scanner: ^2.0.0  # Use the version that is compatible with your Flutter version
  social_media_buttons: ^1.0.0
  share_plus: ^10.1.3
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  pdf: ^3.10.4
  path_provider: ^2.1.1
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^5.0.10
  mailer: ^6.0.1
  url_launcher: ^6.2.1
  build_runner: ^2.4.6
  flutter_local_notifications: ^17.2.2
  firebase_analytics: ^11.3.0
  firebase_messaging: ^15.1.0
  google_mobile_ads: ^5.1.0
  lucide_icons: ^0.257.0
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^4.0.4
  firestore_cache: ^2.14.2
  flutter_insta: ^1.0.1
  add_2_calendar: ^3.0.1
  flutter_timezone: ^3.0.1
  firebase_crashlytics: ^4.1.0
  firebase_performance: ^0.10.0+5
  introduction_screen: ^3.1.12
  flutter_downloader: ^1.11.6
  in_app_purchase: ^3.1.13
  open_file: ^3.3.2
  file_picker: ^8.0.0+1
  flutter_file_dialog: ^3.0.2
dev_dependencies:
  envied_generator: ^0.5.1
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/images/1024.png"
  image_path: "assets/images/LogoFINALCIRCLE.png"
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/font/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf
    - family: CenturyGothic
      fonts:
        - asset: assets/font/CenturyGothic.ttf
