// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyvrLwbF0jCptABYtEtxBNVj3wUp8xwEE',
    appId: '1:261791967363:web:6e13fcdad9bdad085bd3b6',
    messagingSenderId: '261791967363',
    projectId: 'cmpet-65cfd',
    authDomain: 'cmpet-65cfd.firebaseapp.com',
    databaseURL: 'https://cmpet-65cfd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cmpet-65cfd.appspot.com',
    measurementId: 'G-VJQPQ3HPXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGv3b7wHMAotwZNw6gj2j4Xna3YRgc0Sw',
    appId: '1:261791967363:android:0b9cef62d97c37945bd3b6',
    messagingSenderId: '261791967363',
    projectId: 'cmpet-65cfd',
    databaseURL: 'https://cmpet-65cfd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cmpet-65cfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZiv3mnbKYiPrikdG1OOwZPcMBzRK4c5o',
    appId: '1:261791967363:ios:0ab0d5ae59a832185bd3b6',
    messagingSenderId: '261791967363',
    projectId: 'cmpet-65cfd',
    databaseURL: 'https://cmpet-65cfd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cmpet-65cfd.appspot.com',
    iosClientId: '261791967363-v4tgpq8a58iaqrqktav2ojkd7fl4qm0e.apps.googleusercontent.com',
    iosBundleId: 'com.cmpets.app',
  );
}
